-- ═══════════════════════════════════════════════════════════════════════
-- Migration 005: Geo-Spatial Mapping & Epidemiological Dispersion Module
-- ═══════════════════════════════════════════════════════════════════════
-- Adds sub-zone (sub-plot) management, time-series zone telemetry,
-- disease reporting with epidemic tracking, and geo-spatial alerts.
--
-- IMPORTANT: This migration assumes the `fields` table already exists
-- (created by run-migration.js). Run run-migration.js FIRST, then
-- apply this file.
--
-- Adapted from SADD spec to the existing pg Pool architecture.
-- All coordinate data is stored as GeoJSON Geometry Objects in JSONB.
-- ═══════════════════════════════════════════════════════════════════════

-- ── Zone Status Enum ──────────────────────────────────────────────────
-- Mirrors the ZoneStatus enum from the SADD (HEALTHY, WARNING, INFECTED).
-- Using a CHECK constraint instead of CREATE TYPE for simpler migrations.
-- ──────────────────────────────────────────────────────────────────────

-- ── Sub-Zones (Sub-Plots within a Field) ─────────────────────────────
-- Each field can be divided into multiple sub-zones, each with its own
-- crop type, planting date, GeoJSON polygon boundary, and health status.
--
-- NOTE: field_id is UUID to match fields.id which uses gen_random_uuid().
-- ──────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS sub_zones (
  id                SERIAL PRIMARY KEY,
  field_id          UUID NOT NULL REFERENCES fields(id) ON DELETE CASCADE,
  crop_type         VARCHAR(100) NOT NULL,                          -- e.g., "Tomato", "Maize", "Rice"
  boundary          JSONB NOT NULL,                                 -- GeoJSON Polygon/MultiPolygon: { "type": "Polygon", "coordinates": [...] }
  status            VARCHAR(20) NOT NULL DEFAULT 'HEALTHY'          -- 'HEALTHY' | 'WARNING' | 'INFECTED'
    CHECK (status IN ('HEALTHY', 'WARNING', 'INFECTED')),
  planting_date     TIMESTAMP,
  fertilize_freq    INTEGER NOT NULL DEFAULT 14,                    -- Fertilization frequency in days
  spray_freq        INTEGER NOT NULL DEFAULT 10,                    -- Pesticide spray frequency in days
  created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sub_zones_field_id ON sub_zones(field_id);

-- ── Zone Metrics (Time-Series Telemetry per Sub-Zone) ────────────────
-- Stores periodic environmental readings for each sub-zone.
-- In production these come from IoT sensors; during verification they
-- are generated by MockMetricService sinusoidal simulation.
-- ──────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS zone_metrics (
  id              SERIAL PRIMARY KEY,
  sub_zone_id     INTEGER NOT NULL REFERENCES sub_zones(id) ON DELETE CASCADE,
  health_score    INTEGER NOT NULL CHECK (health_score BETWEEN 0 AND 100),
  temperature     NUMERIC(5, 2) NOT NULL,                           -- Celsius
  humidity        NUMERIC(5, 2) NOT NULL,                           -- Percentage
  soil_moisture   NUMERIC(5, 2) NOT NULL,                           -- Percentage
  ph              NUMERIC(4, 2) NOT NULL,                           -- pH level
  ec              NUMERIC(5, 2) NOT NULL,                           -- Electrical Conductivity (dS/m)
  created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Optimised index for fetching latest metrics per sub-zone
CREATE INDEX IF NOT EXISTS idx_zone_metrics_sub_zone_created
  ON zone_metrics(sub_zone_id, created_at DESC);

-- ── Disease Reports ──────────────────────────────────────────────────
-- Records disease occurrences detected within a sub-zone, either from
-- the AI inference pipeline or manual farmer input.
-- ──────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS disease_reports (
  id              SERIAL PRIMARY KEY,
  sub_zone_id     INTEGER NOT NULL REFERENCES sub_zones(id) ON DELETE CASCADE,
  disease_type    VARCHAR(255) NOT NULL,                            -- Name of detected pathogen/pest
  is_resolved     BOOLEAN NOT NULL DEFAULT FALSE,
  created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_disease_reports_sub_zone_id ON disease_reports(sub_zone_id);

-- ── Zone Alerts (Epidemic Broadcast Notifications) ───────────────────
-- Generated when the epidemic dispersion model detects that a sub-zone
-- lies within the danger cone of a reported disease epicenter.
-- ──────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS zone_alerts (
  id                  SERIAL PRIMARY KEY,
  sub_zone_id         INTEGER NOT NULL REFERENCES sub_zones(id) ON DELETE CASCADE,
  disease_report_id   INTEGER NOT NULL REFERENCES disease_reports(id) ON DELETE CASCADE,
  threat_level        VARCHAR(20) NOT NULL DEFAULT 'WARNING'        -- 'WARNING' | 'CRITICAL'
    CHECK (threat_level IN ('WARNING', 'CRITICAL')),
  message             TEXT,
  is_read             BOOLEAN NOT NULL DEFAULT FALSE,
  created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_zone_alerts_sub_zone_id ON zone_alerts(sub_zone_id);
CREATE INDEX IF NOT EXISTS idx_zone_alerts_disease_report_id ON zone_alerts(disease_report_id);
